blog_eloquently/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    patch 'add_tag/:tag_id', on: :member, action: 'add_tag', as: 'tag'
  end

  resources :comments, only: [:destroy, :create]

  root 'posts#index'

end

blog_eloquently/app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    validates_presence_of :author_name
    validates_presence_of :content
    validates_presence_of :post_id
end

blog_eloquently/app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    has_and_belongs_to_many :tags

    validates_presence_of :content
end

blog_eloquently/app/models/tag.rb
class Tag < ActiveRecord::Base
    has_and_belongs_to_many :posts
end

blog_eloquently/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog_eloquently/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog_eloquently/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)
        @comment.save!
        
        redirect_to @comment.post
    end
    
    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        
        redirect_to @comment.post
    end 
    
    
    def comment_params
        params.require(:comment).permit(:author_name, :content, :post_id)
    end
end

blog_eloquently/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :add_tag]
    
    #before_action :authenticate_user!, only: [:new, :create, :edit, :update]


    def index
        @posts = Post.all
    end

    def show
        @comment = Comment.new
        @comments = @post.comments
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.save

        redirect_to @post
    end

    def edit
    end

    def update
        @post.update_attributes(post_params)
        @post.save

        redirect_to @post
    end

    def destroy
        @post.destroy

        redirect_to posts_path
    end

    def add_tag
        @tag = Tag.find(params[:tag_id])
        @post.tags << @tag
        redirect_to @post
    end

    def find_post
        @post = Post.find(params[:id])
    end

    # strong parameters
    def post_params
        params.require(:post).permit(:title, :content)
    end
end

blog_eloquently/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_eloquently/app/helpers/comments_helper.rb
module CommentsHelper
end

blog_eloquently/app/helpers/posts_helper.rb
module PostsHelper
end

blog_eloquently/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogEloquently</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <a href=<%= root_path %> class="navbar-brand">
                Our Blog
            </a>
            <ul class="nav navbar-nav">
                <% if current_user.nil? %>
                    <li><%= link_to("Log in", new_user_session_path) %></li>
                    <li><%= link_to("Sign up", new_user_registration_path) %></li>
                <% else %>
                    <li>Welcome <%= current_user.email %>.</li>
                    <li>%= link_to("Log out", destroy_user_session_path, method: :delete) %></li>
                <% end %>
            </ul>
        </div>
    </nav>
    <% if notice or alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class="container">
        <%= yield %>
    </div>
</body>
</html>

blog_eloquently/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <%= f.label :title %>
    <br />
    <%= f.text_field :title %>
    <br />
    <%= f.label :content %>
    <br />
    <%= f.text_area :content %>
    <br />
    <%= f.submit %>
<% end %>

blog_eloquently/app/views/posts/edit.html.erb
<h1>Edit Post <%= @post.id %></h1>

<%= render 'form' %>

blog_eloquently/app/views/posts/index.html.erb
<h1>Posts</h1>
<p>This is a list of posts on our blog.</p>

<div>
    <%= link_to("New post", new_post_path, class: 'btn btn-primary') %>
</div>

<hr />

<div class="posts-gallery">
    <% @posts.each do |p| %>
        <div class="gallery-item">
            <%= link_to(p.title, p) %>
        </div>
    <% end %>
</div>

blog_eloquently/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

blog_eloquently/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<hr />
Post has these tags: <br />
<%= @post.tags.map(&:name).join(', ') %>
<hr />
<div>
    <%= @post.content %>
</div>
<hr />
<div>
    <%= link_to("All posts", posts_path) %> |
    <%= link_to("Edit post", edit_post_path(@post)) %> |
    <%= link_to("Delete post", post_path(@post), method: :delete) %>
</div>

<hr />
<h5>Choose tags</h5>
<% Tag.all.each do |tag| %>
    | <%= link_to(tag.name, tag_post_path(id: @post.id, tag_id: tag.id), method: :patch) %>
<% end %>
|
<hr />

<% @comments.each do |c| %>
    <p><b><%= c.author_name %></b></p>
    <p><%= c.content %></p>
    <p><%= link_to("Delete comment", comment_path(c), method: :delete) %></p>
    <hr />
<% end %>

<%= form_for @comment do |f| %>
    <%= f.label :author_name %>
    <br />
    <%= f.text_field :author_name %>
    <br />
    <%= f.label :content %>
    <br />
    <%= f.text_area :content %>
    <br />
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit %>
<% end %>